export const comments = [
  "It went through such rapid contortions",
  "She glanced up into the sky to watch the clouds taking shape.",
  "She was aware that things could go wrong. At this point, she had no idea just how wrong everything would go that day.",
  "She put the pen to paper but she couldn't bring herself.",
  "Dragons don't exist they said. They are the stuff of legend and people's imagination. But now that there was a dragon staring directly into his eyes",
  "She didn't like the food a word.",
  "Then came the night of the first falling star. It seemed that it fell to earth about one hundred miles east of him.",
  "He walked down the steps from the train station seem possible. He was about to turn and be on his way when a deep chill filled his body.",
  "The leather jacked showed the scars of being his favorite for years. It wore those scars with pride, feeling that.",
  "Was it a whisper or was it the wind?.",
  "A long black shadow slid across the pavement'",
  "'So, what do you think?' he asked nervously. He wanted to know the answer, but at the same time, he didn't. He'd put his heart and soul into.",
  "The words hadn't flowed from his fingers for the past few weeks blank.",
  "The words hadn't flowed from his fingers for the past few weeks.",
  "It was a question of which of the two she preferred. On the one hand, the choice seemed simple.",
  "Twenty-five stars were neatly placed on the piece of paper. There was room for five more stars but they would be difficult ones to earn.",
  "He heard the crack echo in the late afternoon about a mile away. His heart started racing and he bolted into a full sprint. 'It wasn't a gunshot, it wasn't a gunshot.",
  "She was aware that things could go wrong. In fact.",
  "Benny was tired. Not the normal every day tired All he wanted to do was sit in front of the TV,",
  "The robot clicked disapprovingly, gurgled briefly inside its cubical interior and extruded a pony glass of brownish liquid. 'Sir, you will glass across the table.",
];
