import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "./providers/appprovider";

export const metadata: Metadata = {
  title: "Facebook Clone App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
