import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "./components/home/navbar";
import AppProvider from "./providers/appprovider";

export const metadata: Metadata = {
  title: "Facebook Clone App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <AppProvider>
          <TopBar />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
